### ISSUE TITLE
Getting started instructions

### ISSUE THREAD

**Issue by Jbarget** [fac-12/FAC-Events-Search#66]
Just tried to start the app but getting an error when running `npm run dev`

Steps i took:
- clone the repo
- npm i
- npm run dev

Its a really good habit to have and maintain some getting started instructions in the README so that anyone who joins a project wont have issues getting up and running

In general your readme could do with a bit of love

**Comment by Jbarget** [comment]
oh i need keys
https://github.com/fac-12/FAC-Events-Search/blob/master/config/keys.js

**Comment by shannonjensen** [comment]
Ah so sorry Justen. Didn't see this until now. Will take care of this afternoon. Apologies.

**Comment by shannonjensen** [comment]
See gitter chat

**Comment by Jbarget** [comment]
no problemo, see the README was updated 👍 
but still missing a Getting Started guide (a list of instructions to getting the app up and running)
